package com.test.domain;

import java.util.Date;

public class Goods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private Long goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsname
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String goodsname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.price
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.saleprice
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String saleprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.categoryid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private Integer categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.remark
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goodsinfo
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String goodsinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.photosrc
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String photosrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.status
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.createtime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.altertime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private Date altertime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsid
     *
     * @return the value of goods.goodsid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public Long getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsid
     *
     * @param goodsid the value for goods.goodsid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setGoodsid(Long goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsname
     *
     * @return the value of goods.goodsname
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsname
     *
     * @param goodsname the value for goods.goodsname
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.price
     *
     * @return the value of goods.price
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.price
     *
     * @param price the value for goods.price
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.saleprice
     *
     * @return the value of goods.saleprice
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getSaleprice() {
        return saleprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.saleprice
     *
     * @param saleprice the value for goods.saleprice
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setSaleprice(String saleprice) {
        this.saleprice = saleprice == null ? null : saleprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.categoryid
     *
     * @return the value of goods.categoryid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.categoryid
     *
     * @param categoryid the value for goods.categoryid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.remark
     *
     * @return the value of goods.remark
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.remark
     *
     * @param remark the value for goods.remark
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goodsinfo
     *
     * @return the value of goods.goodsinfo
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getGoodsinfo() {
        return goodsinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goodsinfo
     *
     * @param goodsinfo the value for goods.goodsinfo
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setGoodsinfo(String goodsinfo) {
        this.goodsinfo = goodsinfo == null ? null : goodsinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.photosrc
     *
     * @return the value of goods.photosrc
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getPhotosrc() {
        return photosrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.photosrc
     *
     * @param photosrc the value for goods.photosrc
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setPhotosrc(String photosrc) {
        this.photosrc = photosrc == null ? null : photosrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.status
     *
     * @return the value of goods.status
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.status
     *
     * @param status the value for goods.status
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.createtime
     *
     * @return the value of goods.createtime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.createtime
     *
     * @param createtime the value for goods.createtime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.altertime
     *
     * @return the value of goods.altertime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public Date getAltertime() {
        return altertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.altertime
     *
     * @param altertime the value for goods.altertime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setAltertime(Date altertime) {
        this.altertime = altertime;
    }
}