package com.test.domain;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.name
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.goodid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String goodid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.createtime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.name
     *
     * @return the value of message.name
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.name
     *
     * @param name the value for message.name
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.goodid
     *
     * @return the value of message.goodid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.goodid
     *
     * @param goodid the value for message.goodid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setGoodid(String goodid) {
        this.goodid = goodid == null ? null : goodid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.createtime
     *
     * @return the value of message.createtime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.createtime
     *
     * @param createtime the value for message.createtime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}