package com.test.domain;

public class OrdersBatchctl {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_batchctl.orderserno
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String orderserno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_batchctl.address
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_batchctl.telphone
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String telphone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_batchctl.orderserno
     *
     * @return the value of orders_batchctl.orderserno
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getOrderserno() {
        return orderserno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_batchctl.orderserno
     *
     * @param orderserno the value for orders_batchctl.orderserno
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setOrderserno(String orderserno) {
        this.orderserno = orderserno == null ? null : orderserno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_batchctl.address
     *
     * @return the value of orders_batchctl.address
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_batchctl.address
     *
     * @param address the value for orders_batchctl.address
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_batchctl.telphone
     *
     * @return the value of orders_batchctl.telphone
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_batchctl.telphone
     *
     * @param telphone the value for orders_batchctl.telphone
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }
}