package com.test.domain;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ordersid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private Long ordersid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.goodsid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private Long goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.count
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.email
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.unitprice
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String unitprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.totalprice
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.createtime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.altertime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private Date altertime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.settletime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private Date settletime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderserno
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    private String orderserno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ordersid
     *
     * @return the value of orders.ordersid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public Long getOrdersid() {
        return ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ordersid
     *
     * @param ordersid the value for orders.ordersid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setOrdersid(Long ordersid) {
        this.ordersid = ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.goodsid
     *
     * @return the value of orders.goodsid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public Long getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.goodsid
     *
     * @param goodsid the value for orders.goodsid
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setGoodsid(Long goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.count
     *
     * @return the value of orders.count
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.count
     *
     * @param count the value for orders.count
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setCount(String count) {
        this.count = count == null ? null : count.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.email
     *
     * @return the value of orders.email
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.email
     *
     * @param email the value for orders.email
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.unitprice
     *
     * @return the value of orders.unitprice
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getUnitprice() {
        return unitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.unitprice
     *
     * @param unitprice the value for orders.unitprice
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setUnitprice(String unitprice) {
        this.unitprice = unitprice == null ? null : unitprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.totalprice
     *
     * @return the value of orders.totalprice
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.totalprice
     *
     * @param totalprice the value for orders.totalprice
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setTotalprice(String totalprice) {
        this.totalprice = totalprice == null ? null : totalprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.createtime
     *
     * @return the value of orders.createtime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.createtime
     *
     * @param createtime the value for orders.createtime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.altertime
     *
     * @return the value of orders.altertime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public Date getAltertime() {
        return altertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.altertime
     *
     * @param altertime the value for orders.altertime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setAltertime(Date altertime) {
        this.altertime = altertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.settletime
     *
     * @return the value of orders.settletime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public Date getSettletime() {
        return settletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.settletime
     *
     * @param settletime the value for orders.settletime
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setSettletime(Date settletime) {
        this.settletime = settletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderserno
     *
     * @return the value of orders.orderserno
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public String getOrderserno() {
        return orderserno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderserno
     *
     * @param orderserno the value for orders.orderserno
     *
     * @mbg.generated Fri Mar 09 15:36:28 CST 2018
     */
    public void setOrderserno(String orderserno) {
        this.orderserno = orderserno == null ? null : orderserno.trim();
    }
}